--- # 5.10
    # autor: Piotr Koska
    # copyright: videopoint
    
- hosts: localubuntu
  become: yes
  tasks: 
    - name: install software from list
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - htop
        - vim
        - elinks