--- # 5.16

- hosts: localubuntu
  become: yes
  vars:
    target_service: apache2
  tasks:
    - name: Install Software
      block:
        - service: 
            name: "{{ target_service }}"
            state: started
          register: service_status
      rescue:
        - debug:
            var: service_status
      always: 
        - debug:
            msg: "Tried to ensure service was running"