--- # 5.20
    # autor: Piotr Koska
    # copyright: videopoint
    
- hosts: localcentos
  tasks:
    - name: Run sleep.sh
      command: /home/ubuntu/sleep.sh
      async: 60
      poll: 0
      delegate_to: localubuntu
      run_once: yes

    - name: install httpd
      package: 
        name: httpd
        state: latest
      become: yes