--- # 5.7 Variables in Playbook

- hosts: localubuntu
  tasks:
  - name: create working girectory
    file:
      name: "{{ working_dir }}"
      state: directory
  - name: write service list
    lineinfile:
      path: "{{ working_dir }}/services.txt"
      create: yes
      line: "{{ service_list }}"
  - name: viwe share property
    command: ls -la "{{ shared_paths['nfs'] }}"
    register: cmd_output
    ignore_errors: yes
  - name: write command module output to file
    copy:
      content: "{{ cmd_output }}"
      dest: "{{ working_dir }}/cmd_output.txt"