--- # Nagłowek naszego Playbooka (zaczyna sie od ---).

- name: INSTALL ON HOST VIDEOPOINT1 UBUNTU # PLAY 1
  hosts: videopoint
  become: yes
  # SETUP MODULE
  gather_facts: yes # właczone
  vars:
    server_www_ubuntu: apache2

  tasks:
  - debug:
      msg: "Your host is {{ ansible_host }} IP {{ ansible_all_ipv4_addresses }}"

  # Install python apt
  - name: Install python-apt
    apt:
      name: python-apt
      state: latest

  - name: Install python3-apt
    apt:
      name: python3-apt
      state: latest
  # Install apache
  - name: Install apache2 latest.
    apt:
      name: "{{ server_www_ubuntu }}"
      state: latest

- name: INSTALL ON HOST VIDEOPOINT2 CENTOS # PLAY 2
  hosts: videopoint2
  become: true
  vars:
    server_www_centos: httpd
  gather_facts: no
  
  tasks:
    - debug:
        msg: "Your host is {{ ansible_host }} IP {{ ansible_all_ipv4_addresses }}"

    - name: Install httpd (www server on centos)
      yum:
        name: "{{ server_www_centos }}"
        state: latest